songs = [
    ['', 'Lg79s_2x-xI'],
    //fnaf 1
    ['Remake 1 (Remaster Main Menu) - Five Nights at Freddy＇s', '42XaoDoaZU4'],

    //fnaf 2
    ['Remake 2 (Remaster Main Menu) - Five Nights at Freddy＇s 2 / Curse of Dreadbear', 'ZU7bdcWZcMc'],

    //fnaf 3
    ['Remake 3 (Remaster Main Menu) - Five Nights at Freddy＇s 3', 'xIBHqnQxWGU'],
    ['Good Ending (Remaster Main Menu) - Five Nights at Freddy＇s 3', 'K_QJCa-NbyI'],

    //fnaf 2
    ['Remake 4 (Remaster Main Menu) - Five Nights at Freddy＇s 4', 'E5DLX3n6JOE'],

    //fnaf world
    ['One for the Road - FNaF World', 'Lg79s_2x-xI'],
    ['Running Lights - FNaF World', 'f5x4xXcojnA'],
    ['8Bit Travel Theme - FNaF World', '3OWNxHpDp40'],
    ['Adventure Ahead - FNaF World', 'amwTUOzsplY'],
    ['Battle Victory - FNaF World', 'j1t7FAAuF2Q'],
    ['Snowpiercer - FNaF World', 'zkEUM24alX8'],
    ['Melting Titanium - FNaF World', 'jLlShmZ_iVE'],
    ['Underneath 1 - FNaF World', 'RpL9RsjHIFA'],
    ['The Tower of Majdel Shams - FNaF World', 'yvR3f-m9Uuk'],
    ['Ice Dungeon - FNaF World', 'UGSl5ix_xEo'],
    ['Emerald Waterfalls - FNaF World', '3-pMrzV8rm8'],
    ['Bending Flame - FNaF World', 'uu3WTbNH1So'],
    ['Underneath 2 - FNaF World', 'vBvmnIhse8k'],
    ['Underneath 3 - FNaF World', 'Jh2nycz8hZc'],
    ['8Bit Travel Theme 2 - FNaF World', 'IF_-d1lNwtc'],
    ['Broken 8-Bit Theme - FNaF World', 'FLtnDlyeNeM'],
    ['Inverse - FNaF World', 'qVKDtLxmEOE'],
    ['Inverse Battle - FNaF World', 'l4IJ3O2vvVo'],
    ['Stone Cold - FNaF World', '8av8g7eYq_8'],
    ['Fear of Pixelation - FNaF World', 'JNkwyl9k1WE'],
    ['Frozen Time / Ice Cave (Unused) - FNaF World', 'mB88_r8TviU'],
    ['Broken Crushed and Burned (Unused) - FNaF World', 'dgo3TI9bv_I'],
    ['Don＇t Open The Door - FNaF World', 'yEKY7_MnH4A'],
    ['Darkness Ahead - FNaF World', 'lK221-dMKX8'],
    ['Bluster Cluster - FNaF World', 'tdbc2gD5vr8'],
    ['Boiling Point - FNaF World', '-m76E9VM9hg'],
    ['Boiling Boss - FNaF World', 'UG57G9kbeAs'],
    ['Fearless Fighter - FNaF World', 'b2oBvaF0oLM'],
    ['Rainbow - FNaF World', 'KFmaYWIlGgY'],
    ['Black Lava - FNaF World', 'V73UbUcmEb8'],

    //sister location
    ['Gradual Liquidation - Five Nights at Freddy＇s: Sister Location', 'yI4mwAR7beo'],
    ['Shift Start Jingle - Five Nights at Freddy＇s: Sister Location', 'fm73QMZZ8'],
    ['Shift Complete Jingle - Five Nights at Freddy＇s: Sister Location', '98e_hmMR838'],
    ['Dramatic Soap Opera - Five Nights at Freddy＇s: Sister Location', 'ia9XoNb8V00'],
    ['Crumbling Dreams - Five Nights at Freddy＇s: Sister Location', '1rR80LYo95E'],
    ['Casual Bongos - Five Nights at Freddy＇s: Sister Location', 'KXisdpP0K04'],
    ['Turtle Crusher - Five Nights at Freddy＇s: Sister Location', 'AZf0_Oq9nhc'],
    ['Watch your 6 - Five Nights at Freddy＇s: Sister Location', 'L4SsmVeA9S4'],
    ['Custom Menu - Five Nights at Freddy＇s: Sister Location', 'hYVK0uyWq7g'],
    ['Venta Black Desire - Five Nights at Freddy＇s: Sister Location', 'i4XFFslLDJk'],
    ['The Forbidden Nocturne - Five Nights at Freddy＇s: Sister Location', 'xqjnaajZPSk'],
    ['Drag Me to the Crusher - Five Nights at Freddy＇s: Sister Location', 'UpCpPkIwfuE'],
    ['MVP Show Off - Five Nights at Freddy＇s: Sister Location', 'em2ciDyjBlk'],
    ['Demolition Inevitable - Five Nights at Freddy＇s: Sister Location', 'N13jzVyl9-4'],
    ['The Raid (Trailer Music) - Five Nights at Freddy＇s: Sister Location', 'D9oe3Z7VDwM'],

    //ffps
    ['Fits Me Like A Glove (Title Screen) - Freddy Fazbear＇s Pizzeria Simulator', '6hzW2J_gYic'],
    ['Swallowed By The Void - Freddy Fazbear＇s Pizzeria Simulator', 'Hic81gEb-4Q'],
    ['Forgotten Sunday Show - Freddy Fazbear＇s Pizzeria Simulator', 'lx6ZVD0Nc4k'],
    ['Creme De La Creme - Freddy Fazbear＇s Pizzeria Simulator', '1YdrIEYhCpI'],
    ['Thank You For Your Patience - Freddy Fazbear＇s Pizzeria Simulator', '-PUTSTRfJm8'],
    ['Just Add Water - Freddy Fazbear＇s Pizzeria Simulator', 'YLH4KF9B3l0'],
    ['A Slice and a Scoop - Freddy Fazbear＇s Pizzeria Simulator', 'lrCVPDjovnk'],
    ['Minor Corrosion of the Bizet - Freddy Fazbear＇s Pizzeria Simulator', '6LjtvZAtURg'],
    ['Four Bits to the Left - Freddy Fazbear＇s Pizzeria Simulator', 'GcgR5CytkNU'],
    ['Four Bits to the Left V2 - Freddy Fazbear＇s Pizzeria Simulator', 'qTsRRuiFjIA'],
    ['Four Bits to the Left V3 - Freddy Fazbear＇s Pizzeria Simulator', 'y1jEVvc9paM'],
    ['240 Bits Per Mile - Freddy Fazbear＇s Pizzeria Simulator', 'zcjLldhJCLE'],
    ['Smashing Windshields - Freddy Fazbear＇s Pizzeria Simulator', 'KJYsTbhzjHk'],
    ['No Time For Popcorn - Freddy Fazbear＇s Pizzeria Simulator', 'KA9U4gK4WTQ'],
    ['Groovy Gravy - Freddy Fazbear＇s Pizzeria Simulator', 'jZXXdKfN9u4'],
    ['The Runaway - Freddy Fazbear＇s Pizzeria Simulator', 'xuC3ZwwZdPQ'],
    ['Alchemists Fantasy - Freddy Fazbear＇s Pizzeria Simulator', 'VvnnKKXHp8E'],
    ['Win Game - Freddy Fazbear＇s Pizzeria Simulator', 'HC2McVTQEbA'],
    ['Legal Woes - Freddy Fazbear＇s Pizzeria Simulator', 'x1fNFs7t33c'],
    ['Nowhere To Run - Freddy Fazbear＇s Pizzeria Simulator', 'tZI2ATLcKnw'],
    ['Necessary Evil (Credits) - Freddy Fazbear＇s Pizzeria Simulator', '9wz40rCB_rI'],

    //ucn
    ['Eisoptrophobia - Ultimate Custom Night', '1n8V9lA4Y4Y'],
    ['Where Dreams Die - Ultimate Custom Night', 'IBBy6R5CMx4'],
    ['Hybernating Evil - Ultimate Custom Night', 'qiEzTBn5tYY'],
    ['Sonata for the Fallen - Ultimate Custom Night', 'LvVKmr7MgCg'],
    ['Sleep No More - Ultimate Custom Night', 'oY63sIVzUMY'],
    ['Last Breath - Ultimate Custom Night', '5dCXcA-XW0k'],
    ['High Score - Ultimate Custom Night', '1cxAX5cu58E'],
    ['Freddy Theme - Ultimate Custom Night', 'DlAPYAZFREQ'],
    ['Foxy Theme - Ultimate Custom Night', 'EWqbzLQG2w4'],
    ['Highschool Days - Ultimate Custom Night', 'n1MguAC_H28'],
    ['Void - Ultimate Custom Night', '5kV4oFOGSd0'],

    //help wanted
    ['Freddy Fazbear Theme / Showtime (Draft) - Five Nights at Freddy＇s: Help Wanted', '8Tbll443aSk'],
    ['Freddy Fazbear Theme / Showtime (Rock Mix) - Five Nights at Freddy＇s: Help Wanted', 'vvMRO0hKSF4'],
    ['Twisted Birthday - Five Nights at Freddy＇s: Help Wanted', 'PhK_EhiWjY4'],
    ['Dead Eyes - Five Nights at Freddy＇s: Help Wanted', 'cp1qmZrBGN0'],
    ['Bonnie Nightmare Clash - Five Nights at Freddy＇s: Help Wanted', 'AbuC1ooOLkw'],

    //special delivery
    ['Dangerous Thoughts - Five Nights at Freddy＇s: Special Delivery', 'hBeJXQlF22M'],
    ['Dark Circus: Encore! (Unused) - Five Nights at Freddy＇s: Special Delivery', 'RwHTx_s2Ddg'],
    ['Mangle Teaser Video Music - Five Nights at Freddy＇s: Special Delivery', 'Q2IpypM4JtY'],
    ['The Sound of Falling (Unused) - Five Nights at Freddy＇s: Special Delivery', 'CdGqLyk9RbM'],
        //maybe stock tracks
    ['Game Intro / "Lucky" - Five Nights at Freddy＇s: Special Delivery', 'yhYy8YBZ0iI'],
    ['Inbox - Five Nights at Freddy＇s: Special Delivery', 'LtjKol5_5mE'],
        //definitely stock tracks
    ['Shop - Five Nights at Freddy＇s: Special Delivery', 'WHDSNxktrGM'],

    //freddy in space 2
    ['Purple Smasher - Freddy in Space 2', '49glGUHi2g8'],
    ['Rebel Son - Freddy in Space 2', 'hEMeW034bHE'],
    ['A Gun in a Knife Fight - Freddy in Space 2', 'kgUJKqOef_4'],
    ['Too Many Light Years - Freddy in Space 2', 'EGoWTgRB59k'],
    ['Into the Unknown - Freddy in Space 2', '64MI7S7dE9E'],
    ['Star Dazzled - Freddy in Space 2', 'jQY-hz-NJUg'],
    ['Liquid Polyphony - Freddy in Space 2', 'GyBauUDqf9A'],
    ['Blazing Horizon - Freddy in Space 2', 'dQy_RtE9wvo'],
    ['Deceptive Andromeda - Freddy in Space 2', '2oZimdukouQ'],
    ['Through the Cracks - Freddy in Space 2', 'nLHB8zbjeBI'],
    ['Inbetween Two Worlds - Freddy in Space 2', 'VdUiKBNYpbQ'],
    ['Fine Dierum - Freddy in Space 2', 'S6_aMe2tA7k'],
    ['Steam Powered Punk - Freddy in Space 2', 'ZMME9MINA7w'],
    ['Rust Under the Skin - Freddy in Space 2', 'BsXhX7o9_jg'],
    ['The Colder Stone - Freddy in Space 2', 'taSCZxgoXuE'],
    ['Warewolf Behind 18 Bars - Freddy in Space 2', 'SfsovVRRe0o'],
    ['Acrophobia - Freddy in Space 2', 'EZ_wWUak-7Q'],
    ['Dark Agglomeration - Freddy in Space 2', '0EvWij84t0k'],
    ['DrainStorm - Freddy in Space 2', 'U06mDEr-2L4'],
    ['Passive Aggressive - Freddy in Space 2', '0PGW4gL9LaI'],
    ['Supernova Journey - Freddy in Space 2', 'nTus6m6HzFM'],
    ['Level Complete - Freddy in Space 2', 'O4IOVxPdyOs'],
    ['Power Up 5 Jingle (Power Up) - Freddy in Space 2', 'dOgkbEn39cc'],
    ['Power Up 1 Jingle (Treasure) - Freddy in Space 2', 'UZfdQ0vW5mE'],
    ['We Made it After All - Freddy in Space 2', 'ppfsA-SRHK0'],
    ['The Wrong Party (Unused) - Freddy in Space 2', 'em0SXJUhi58'],

    //furys rage
    ['Night Drive with the Gang - Security Breach: Fury＇s Rage', 'LNRUD6atub4'],
    ['Midnight Prowler - Security Breach: Fury＇s Rage', 'cqlpuoZO_3Y'],
    ['A Hunter Never Dreams - Security Breach: Fury＇s Rage', 'PuKxyP_p4Ks'],
    ['A Fox in a City of Wolves - Security Breach: Fury＇s Rage', '6KixioTb6WI'],
    ['Kicks and Bricks and Dirty Tricks - Security Breach: Fury＇s Rage', 'JN6qlFLl-nM'],
    ['Metal Stitches - Security Breach: Fury＇s Rage', 'kZQdOj1xy4M'],
    ['Cybernetic Breakdown - Security Breach: Fury＇s Rage', '0BeGdPkY1t8'],
    ['Scoundrel - Security Breach: Fury＇s Rage', 'CGYIOF2U624'],
    ['Victory Jingle - Security Breach: Fury＇s Rage', 'XFpvgty5z7E'],

    //security breach
    ['Main Theme - Five Nights at Freddy＇s: Security Breach', 'x8BbO2BBSkE'],
    ['Title Screen - Five Nights at Freddy＇s: Security Breach', 'K5AOGSvMlnY'],
    ['Chica Jam - Five Nights at Freddy＇s: Security Breach', 'llYmXUMN_2U'],
    ['Scrap Yard Megalodon - Five Nights at Freddy＇s: Security Breach', 'q2AZz0syLrE'],
    ['Welcome - Five Nights at Freddy＇s: Security Breach', 'TYO_coZx92s'],
    ['Hunted - Five Nights at Freddy＇s: Security Breach', 'ShW3y9sp7g4'],
    ['Daycare Theme - Five Nights at Freddy＇s: Security Breach', 'loe5drHw2Sk'],
    ['Moondrop - Five Nights at Freddy＇s: Security Breach', 'QZc0omBiB_w'],
    ['Vanny Encounter - Five Nights at Freddy＇s: Security Breach', 'M_J-WNXpKYo'],
    ['Elevator Music - Five Nights at Freddy＇s: Security Breach', 'vsN7cKS8blo'],
    ['Prize Box (Main Theme Version) - Five Nights at Freddy＇s: Security Breach', 'f1p7GAgWzno'],
    ['El Chips - Five Nights at Freddy＇s: Security Breach', 'i8W3p5G_Irc'],
    ['Arcade Theme - Five Nights at Freddy＇s: Security Breach', 'hm-IdiEfyv0'],
    ['Space Lobby - Five Nights at Freddy＇s: Security Breach', 'bTouJ_cYzoA'],
    ['Fazerblast Arena / Fazer Blast Jam - Five Nights at Freddy＇s: Security Breach', 'IJM6xsbG1zs'],
    ['Montgomery＇s Golf Swamp - Five Nights at Freddy＇s: Security Breach', '5bLR2aWL7o0'],
    ['Mini-Golf Intro - Five Nights at Freddy＇s: Security Breach', 'pgaqbZY8Ok0'],
    ['D.J. Music Man - Five Nights at Freddy＇s: Security Breach', 'lD3aq4_vDBU'],
    ['The Alley - Five Nights at Freddy＇s: Security Breach', 'vLDtnl37mvo'],
    ['Road Trip - Five Nights at Freddy＇s: Security Breach', 'GmquQn7zY8k'],
    ['V.I.P. - Five Nights at Freddy＇s: Security Breach', 'Eio-RhB5B4Y'],
    ['Freddy - Five Nights at Freddy＇s: Security Breach', 'Rz2GUAZ3qnY'],
    ['Fazerblast - Five Nights at Freddy＇s: Security Breach', 'kF8RbrguoRk'],
    ['Princess Quest Title Theme - Five Nights at Freddy＇s: Help Wanted / Security Breach', 'Vs68mme5SZo'],
    ['Caught in a Loop - Five Nights at Freddy＇s: Help Wanted / Security Breach', 'JmNr2t2hERw'],
    ['Princess Quest Continue Music - Five Nights at Freddy＇s: Help Wanted / Security Breach', 'YwyM9zkzxPA'],
    ['Vanny Redeemed - Five Nights at Freddy＇s: Security Breach', 'Uf9KfuW61F4'],
    ['You＇re My Superstar (Game Edit) - Five Nights at Freddy＇s: Security Breach', 'pivP9uoi7jc'],
    ['Burntrap - Five Nights at Freddy＇s: Security Breach', 'D2uPWjFEONo'],
    ['Burntrap Intro - Five Nights at Freddy＇s: Security Breach', 'a3lZac5rkFY'],
    ['Happy (True) Ending - Five Nights at Freddy＇s: Security Breach', 'VOzqysKGSX0'],
    ['Prize Box (Suspense Version) - Five Nights at Freddy＇s: Security Breach', 'VA-Q_5QdMUg'],
    ['Scratch Marks on the Ceiling (Trailer Music) - Five Nights at Freddy＇s: Security Breach', 'By6RuFr4bnk'],
    ['Hydraulic Jaws (Trailer Music) - Five Nights at Freddy＇s: Security Breach', 'oCZSCURaiHM'],
    ['Freddy & Friends on Tour - Five Nights at Freddy＇s: Security Breach', 'kFu4Kj0P8Cg'],
    ['Forever and Ever - Five Nights at Freddy＇s: Security Breach', 'gwHPtfSBWsc'],
    ['Elevator Music (8-bit Version) - Five Nights at Freddy＇s: Security Breach', '7LIpUk0THSo'],
    ['Elevator Music (Solo Organ Version) (Unused) - Five Nights at Freddy＇s: Security Breach', 'mbJ2hCxnZxM'],
    ['Phantogeusia - Five Nights at Freddy＇s: Security Breach / Help Wanted 2', 'd6iBIFsjVek'],
    ['Snap! Goes the Sfinal Chord (Unused) - Five Nights at Freddy＇s: Security Breach', '63IpQUiwmWo'],
    ['Termination Sequence Regrets (Unused) - Five Nights at Freddy＇s: Security Breach', 'tccSEdtIsFU'],
    ['The Nerve Cutter (Unused) - Five Nights at Freddy＇s: Security Breach', '4gY9kVoM4JY'],
        //ruin
    ['I Got Your Message - Five Nights at Freddy＇s: Security Breach (Ruin)', 'vOjf2OtOutE'],
    ['Concealed Coolness - Five Nights at Freddy＇s: Security Breach (Ruin)', 'H3xPYxEyvIQ'],
    ['Your Special Day - Five Nights at Freddy＇s: Security Breach (Ruin)', 'yQu59ZCJiFI'],
    ['Mimic Chase - Five Nights at Freddy＇s: Security Breach (Ruin)', 'sZMmaK_BNxY'],
    ['Scooper - Five Nights at Freddy＇s: Security Breach (Ruin)', 'p_4UDJAYPN8'],
    ['Credits - Five Nights at Freddy＇s: Security Breach (Ruin)', 'hRYoFc-hs6s'],
    ['Phantom Distortion (Trailer Music) - Five Nights at Freddy＇s: Security Breach (Ruin)', 'nFGFJ0FoCrI'],
    ['Evil Escalations (Switch Trailer) - Five Nights at Freddy＇s: Security Breach (Ruin)', 'pNaWA31mtkA'],
    ['I Remember (B-Side) - Five Nights at Freddy＇s: Security Breach (Ruin)', 'lwukulwDAzU'],
    ['Are You There? (B-Side) - Five Nights at Freddy＇s: Security Breach (Ruin)', 'q9DHZ8KlJmI'],

    //freddy in space 3
    ['Freedom At All Cost - Freddy in Space 3: Chica in Space', 'rKzUXa8kEUU'],
    ['Oh How The Turners Have Tabled - Freddy in Space 3: Chica in Space', '4f6ybCD7pyg'],
    ['From Somewhere To Nowhere - Freddy in Space 3: Chica in Space', 'cXU7vrOyzJo'],
    ['Melting Time Cells - Freddy in Space 3: Chica in Space', 'Wd7mVP8zX6Q'],
    ['Sunday Paraglider - Freddy in Space 3: Chica in Space', 'NCLVTRClQwQ'],
    ['Planet Obliterator 5000 - Freddy in Space 3: Chica in Space', 'qcEZtmH2UYg'],
    ['Class A Annihilation Machine - Freddy in Space 3: Chica in Space', 'qKDki1JoN_M'],
    ['The End of the Tunnel - Freddy in Space 3: Chica in Space', 'iW76SWOPsg0'],
    ['Back From Cryptobiosis - Freddy in Space 3: Chica in Space', 'I36ZCG6PQ1M'],
    ['Random Seizures - Freddy in Space 3: Chica in Space', 'XY2Zyg5Ij1s'],
    ['An Army Of Stompers - Freddy in Space 3: Chica in Space', 'Dw5HAO5EcU8'],
    ['97 115 99 105 105 10 (Merch Cemetery) - Freddy in Space 3: Chica in Space', '6UaOGxUSiB4'],
    ['A Wheel of Shadows - Freddy in Space 3: Chica in Space', 'tviyPJ1GOMk'],
    ['Down The Drain It Goes - Freddy in Space 3: Chica in Space', 'Gujy8hEIv1Q'],
    ['Victory Theme - Freddy in Space 3: Chica in Space', 'z5jAPILf1hU'],

    //help wanted 2
    ['Mystic Hippo - Five Nights at Freddy＇s: Help Wanted 2', 'ZdpT-QkhYbY'],
    ['Fazforce Theme - Five Nights at Freddy＇s: Help Wanted 2', 'B3DTxXwXyeI'],
    ['DJMM - Five Nights at Freddy＇s: Help Wanted 2', 'rTFbh0v-PuU'],
    ['Bonnie Bowl - Five Nights at Freddy＇s: Help Wanted 2', 'Zfd_5gZe4pw'],
    ['Tales from the One-Eyed Cat Tavern - Five Nights at Freddy＇s: Help Wanted 2', 'totOZi83TuM'],
    ['My Grandfather＇s Clock - Five Nights at Freddy＇s: Help Wanted 2', 'i8YoiYEcbWA'],
    ['Doomsday Ride - Five Nights at Freddy＇s: Help Wanted 2', 'pnK9sU2Qowo'],
    ['Scorched Cranberries - Five Nights at Freddy＇s: Help Wanted 2', 'Gep216Lecl4'],
    ['Gracefully Into the Abyss (Reprise) - Five Nights at Freddy＇s: Help Wanted 2', '5pTJHMtAK-I'],
    ['Gracefully Into the Abyss - Five Nights at Freddy＇s: Help Wanted 2', '24GicYTz_6E'],
    ['Graveyard Shift (Unused) - Five Nights at Freddy＇s: Help Wanted 2', 'jCbql9CrDck'],
    ['Gameplay Release Trailer Music - Five Nights at Freddy＇s: Help Wanted 2', 'dRiaeMT3P8A'],
    ['Wrong Impression (Meta Quest Trailer) - Five Nights at Freddy＇s: Help Wanted 2', 'v2keud3HmdM'],
    ['Flat Mode Trailer Music - Five Nights at Freddy＇s: Help Wanted 2', 'KL5znyg9Ryw'],
    ['Crimson Mold (Switch Trailer) - Five Nights at Freddy＇s: Help Wanted 2', 'dkukbyP_pIc'],

    //five laps at freddys
    ['Menu - Five Laps at Freddy＇s', '_3X00SAgEm4'],
    ['Fazbear Hills (Day) - Five Laps at Freddy＇s', 'ie4WFwBL3ws'],
    ['Fazbear Hills (Night) - Five Laps at Freddy＇s', 'OmeGHwnB8Ks'],
    ['Midnight Motorist (Day) - Five Laps at Freddy＇s', 'cMP_EYG878g'],
    ['Midnight Motorist (Night) - Five Laps at Freddy＇s', '4RK62yrqLSo'],
    ['The Sinkhole (Day) - Five Laps at Freddy＇s', '2dyBak-l-IQ'],
    ['The Sinkhole (Night) - Five Laps at Freddy＇s', '0a9YO3UiX18'],
    ['Results Screen - Five Laps at Freddy＇s', 'FD-_qDdcvRc'],

    //into the pit
    ['Title Theme - Five Nights at Freddy＇s: Into the Pit', 'WGI67WJtSpQ'],
    ['Title Theme (Alternative) - Five Nights at Freddy＇s: Into the Pit', 'wcCR6mdnr08'],
    ['X43 - Five Nights at Freddy＇s: Into the Pit', '0o-ljo_P6x0'],
    ['Diner Theme - Five Nights at Freddy＇s: Into the Pit', 'ORkDeWJTS78'],
    ['Diner Theme (Alternative) - Five Nights at Freddy＇s: Into the Pit', '2wLCD3j1pZw'],
    ['Hollow Dance - Five Nights at Freddy＇s: Into the Pit', '0p2OQJcNDRg'],
    ['Hollow Dance (Alternative) - Five Nights at Freddy＇s: Into the Pit', 'BhJHjPXVQB0'],
    ['Arcade Theme - Five Nights at Freddy＇s: Into the Pit', 'xlotQfD6HrE'],
    ['Arcade Theme (Alternative) - Five Nights at Freddy＇s: Into the Pit', 'kTNmTg_awnI'],
    ['Pizzaroller - Five Nights at Freddy＇s: Into the Pit', 'o0NiCG5lBJk'],
    ['Pizzaroller (Alternative) - Five Nights at Freddy＇s: Into the Pit', 'tjNwNO8JAe4'],
    ['Road Crossing / Deliver The Pizza - Five Nights at Freddy＇s: Into the Pit', 'MdfiKeNBRyI'],
    ['Road Crossing / Deliver The Pizza (Alternative) - Five Nights at Freddy＇s: Into the Pit', '3dwILpzRqxg'],
    ['Comets Shooter / Shoot The Space Balloons - Five Nights at Freddy＇s: Into the Pit', 'E3AW7yap2d4'],
    ['Comets Shooter / Shoot The Space Balloons (Alternative) - Five Nights at Freddy＇s: Into the Pit', 'oeQPdBSD3Dk'],
    ['Space Shooter / Fast Food Invader - Five Nights at Freddy＇s: Into the Pit', 'k2ha_VaHFJw'],
    ['Space Shooter / Fast Food Invader (Alternative) - Five Nights at Freddy＇s: Into the Pit', 'UvGeIn8FqnU'],
    ['Heftin＇ With Helpules - Five Nights at Freddy＇s: Into the Pit', 'uig3eFTLLIM'],
    ['Heftin＇ With Helpules (Alternative) - Five Nights at Freddy＇s: Into the Pit', '5eKAv4YW0g8'],
    ['Save Them / Rescue The Children - Five Nights at Freddy＇s: Into the Pit', 'XulSOt4e6FY'],
    ['Save Them / Rescue The Children (Alternative) - Five Nights at Freddy＇s: Into the Pit', '_ne_5NJ65AE'],
    ['Hat Game / Collect The Hats - Five Nights at Freddy＇s: Into the Pit', 'Mi5m6muYHrQ'],
    ['Hat Game / Collect The Hats (Alternative) - Five Nights at Freddy＇s: Into the Pit', 'V6TUjP9p20U'],
    ['Slidey Pieces Puzzle / Solve The Puzzle - Five Nights at Freddy＇s: Into the Pit', 'SgRo6pETx1w'],
    ['Slidey Pieces Puzzle / Solve The Puzzle (Alternative) - Five Nights at Freddy＇s: Into the Pit', 'UL5cbXCoYLc'],
    ['Found His Den (The Poe Poem) - Five Nights at Freddy＇s: Into the Pit', 'MlKNSus1S1g'],
    ['Endless Terror - Five Nights at Freddy＇s: Into the Pit', 'ZI5YIe32dv8'],
    ['Game Over - Five Nights at Freddy＇s: Into the Pit', 'q150ZHUGcV8'],
    ['School Radio Music - Five Nights at Freddy＇s: Into the Pit', 'wgwiDizUfCw'],
    ['School Radio Music (Alternative) - Five Nights at Freddy＇s: Into the Pit', 'e0i5khEYn40'],
    ['Bonnie b good - Five Nights at Freddy＇s: Into the Pit', '3iFyOUomcyU'],
    ['Hobo Dance - Five Nights at Freddy＇s: Into the Pit', 'ULI9Sn-EdvY'],
    ['It＇s All My Fault - Five Nights at Freddy＇s: Into the Pit', 'I5HgL4KYptc'],
    ['Voices From The Pit - Five Nights at Freddy＇s: Into the Pit', 'zD1zXIb9Dhk'],
    ['Calm (She could feel everyone＇s eyes on her) - Five Nights at Freddy＇s: Into the Pit', 'nYNvyZA5z-8'],
    ['Good Ending - Five Nights at Freddy＇s: Into the Pit', 'eA_DMCXVSng'],
    ['Jeff＇s Pizza (Creepy) - Five Nights at Freddy＇s: Into the Pit', '2okqalckpB4'],
    ['How can you sit there and eat pizza - Five Nights at Freddy＇s: Into the Pit', 'UvIIqimEnh0'],

    //fnaf movie
    ['Five Nights at Freddy＇s (Opening) - Five Nights at Freddy＇s (Movie)', 'enZwjmgCahs'],
    ['Diddleedum - Five Nights at Freddy＇s (Movie)', '8qubiP94LzU'],
    ['Delinquent Notice - Five Nights at Freddy＇s (Movie)', '3-_v7NUHRNY'],
    ['Mike＇s Dream Sequence I - Five Nights at Freddy＇s (Movie)', 'nVDQtPCU8dk'],
    ['Mike＇s Dream Sequence II - Five Nights at Freddy＇s (Movie)', 'H8IFxt__ftU'],
    ['Aunt Jane - Five Nights at Freddy＇s (Movie)', 'tA4rTZedYuA'],
    ['Vanessa - Five Nights at Freddy＇s (Movie)', 'aA5rapBdEQw'],
    ['A Way In - Five Nights at Freddy＇s (Movie)', '_zcbiSyTmqc'],
    ['Chica＇s Mischief - Five Nights at Freddy＇s (Movie)', '16yfERtlLLE'],
    ['Foxy Fatality - Five Nights at Freddy＇s (Movie)', 'GzoNMvne71Q'],
    ['Family History - Five Nights at Freddy＇s (Movie)', 'jYAFxgwYeX0'],
    ['Clean Up - Five Nights at Freddy＇s (Movie)', 'LZa2Q558Qqo'],
    ['Fuzzy Friends - Five Nights at Freddy＇s (Movie)', 'ktb_iymqoCY'],
    ['Who Took Garrett? - Five Nights at Freddy＇s (Movie)', 'kLhPlICf3fA'],
    ['Follow The Yellow Rabbit - Five Nights at Freddy＇s (Movie)', 'vnLKzdKpJDA'],
    ['Fuzzy on the Details - Five Nights at Freddy＇s (Movie)', 'sDVaxkL55PE'],
    ['Mike＇s Dream Sequence III - Five Nights at Freddy＇s (Movie)', 'unijXlff9Nw'],
    ['Vannesa＇s Past / Vanessa＇s Past - Five Nights at Freddy＇s (Movie)', 'lTgng5j2mCM'],
    ['Gear Up! - Five Nights at Freddy＇s (Movie)', 'ka4japGpaUk'],
    ['Abby＇s in Danger - Five Nights at Freddy＇s (Movie)', '0csGQ0eBHL8'],
    ['The Yellow Rabbit - Five Nights at Freddy＇s (Movie)', 'DIyonv7II5Y'],
    ['Now I Kill You - Five Nights at Freddy＇s (Movie)', 'TyCXodcQpIk'],
    ['Doing Well - Five Nights at Freddy＇s (Movie)', 'NqRpX00qbZw'],
    ['The Rabbit Lives - Five Nights at Freddy＇s (Movie)', 'C_NuaIu18Jo'],
    ['My Grandfather＇s Clock - Five Nights at Freddy＇s (Movie)', '3TarZctjb5k'],
    ['Official Teaser Music - Five Nights at Freddy＇s (Movie)', 'EGDsaU6_Vy4'],
    ['Official Trailer Music - Five Nights at Freddy＇s (Movie)', 'MCHlP2aPcTg'],
    ['Final Trailer Music - Five Nights at Freddy＇s (Movie)', '5EUV2EYOvQA'],
        //licensed
    ['Too Late For Tears - Five Nights at Freddy＇s (Movie)', 'hArq9n7s4Ro'],
    ['Talking In Your Sleep - Five Nights at Freddy＇s (Movie)', 'psXiG-faVOM'],
    ['Connection - Five Nights at Freddy＇s (Movie)', '4Vlysu352_U'],
    ['Real Wild Child (Wild One) - Five Nights at Freddy＇s (Movie)', 'buOahI4oRF8'],
    ['Celebration - Five Nights at Freddy＇s (Movie)', 'G8i6NIUbaGY'],
    ['I Wanna Be Down - Five Nights at Freddy＇s (Movie)', 'h7hzEKIhYJ4'],
    //['Five Nights at Freddy＇s (The Living Tombstone) - Five Nights at Freddy＇s (Movie)', 'nB3JcY3kMrE'],
        //freddys fanzone
    ['Don＇t Tell Me More - Freddy＇s Fanzone', 'PFshlgCcBK0'],

    //fanverse -------------------------------------------------------------------------------------------------------------------------
    //fnac 1
    ['Menu Theme - Five Nights at Candy＇s Remastered', 'w014WISTHKQ'],
    ['Forgotten Theme - Five Nights at Candy＇s Remastered', 'rnR1Ywy2CUI'],

    //fnac 2
    ['Menu Theme - Five Nights at Candy＇s 2', '5TP9Q9qZSbE'],
    ['Ending Theme - Five Nights at Candy＇s 2', 'QWXpSw1vMxE'],

    //fnac 3
    ['Menu Theme - Five Nights at Candy＇s 3', 'J0JprFuA7iM'],
    ['Safety - Five Nights at Candy＇s 3', 'TuTJm2Uuu0k'],
    ['Dreamscape - Five Nights at Candy＇s 3', 'CGUf5MkzKEA'],
    ['Deepscape - Five Nights at Candy＇s 3', 'KDFvblHcYh0'],
    ['My Sleep Music - Five Nights at Candy＇s 3', '1EMcKhtu52s'],
    ['The Rat & Cat Theater - Five Nights at Candy＇s 3', 'sZcoeUs7dE0'],
    ['Confrontation - Five Nights at Candy＇s 3', 'bm7isGE13HQ'],
    ['The End - Five Nights at Candy＇s 3', 'wWzWLWkucKM'],
    ['Extra Theme - Five Nights at Candy＇s 3', '6-Zt0pSMX9s'],
    ['Fishing with Candy - Five Nights at Candy＇s 3', 'vjQ_oFe3ewI'],
    ['Cindy＇s Garden - Five Nights at Candy＇s 3', 'AYNCOOgIDPg'],
    ['Candy＇s Adventure - The Adventure Begins! - Five Nights at Candy＇s 3', 'qEhtb8eJLQ0'],
    ['Candy＇s Adventure - Under-The-Ground Underground - Five Nights at Candy＇s 3', 'snYH2_drbV8'],
    ['Candy＇s Adventure - The Secret Underground Lair - Five Nights at Candy＇s 3', 'Sj1Dr0Z_9ZY'],
    ['Candy＇s Adventure - Fight Like Cat and Dog - Five Nights at Candy＇s 3', 'dq69QmFoOiI'],
    ['Forgotten - Five Nights at Candy＇s 3', '4xUdWifyEQE'],

    //fnac fur
    ['Title - FNAC FUR', 'Ga5oEWE76ac'],
    ['Home - FNAC FUR', 'hJoP_4i8bms'],
    ['Sweet Hills - FNAC FUR', '7SZjWZrvLCc'],
    ['Cave - FNAC FUR', 'lweOa5zQFCQ'],
    ['The RAT - FNAC FUR', 'qc3SKHriE7s'],
    ['Boss Battle - FNAC FUR', 'SjuVkLv6SxY'],
    ['Frosting Falls Theme - FNAC FUR', 'MOBx4JQLcFo'],
    ['Basement - FNAC FUR', '0T1VT0jX2og'],

    //popgoes arcade
    ['Title Screen - POPGOES Arcade', '6ocY8tdAbNU'],
    ['The Garden - POPGOES Arcade', 'ULbrRP5vq2w'],
    ['West Forest - POPGOES Arcade', 'qtlBgEoMSLU'],
    ['South Forest - POPGOES Arcade', 'NqArVQPIrWQ'],
    ['East Forest - POPGOES Arcade', 'LwEtjr2AmDs'],
    ['North Forest - POPGOES Arcade', 'KxjabzVQkgE'],
    ['The Castle - POPGOES Arcade', 'kqWp1LmotP4'],
    ['Normal Battle - POPGOES Arcade', 'HhpyFhAZF10'],
    ['Rare Battle - POPGOES Arcade', '5DU7kFmjW1Q'],
    ['Gilded Battle - POPGOES Arcade', 'Z2U4W1rwwBM'],
    ['Miniboss Battle - POPGOES Arcade', 'UjbVtdN0SGw'],
    ['Bridge Guard - POPGOES Arcade', 'z_tyQPH_rlQ'],
    ['Final Boss - POPGOES Arcade', 'JUV7avU524I'],
    ['In Its Code - POPGOES Arcade', 'Scte1OFNmrs'],
    ['Directive - POPGOES Arcade', 'dLT2fC16HaI'],
    ['Under the Forest - POPGOES Arcade', 'UB36FmqaDCU'],
    ['Robot Battle - POPGOES Arcade', 'DSBMNxRakTk'],
    ['The Machinist - POPGOES Arcade', 'ah3WoODQeb8'],
    ['Secret Boss - POPGOES Arcade', 'm0cFU1oNWLo'],
    ['To Be Continued - POPGOES Arcade', 'HFcfaa_SMSw'],

    //mypopgoes <--- can you believe it
    ['Attic - myPOPGOES', 'cnLgHVpjtLE'],
    ['Mysterious (Reversed) / Ambience - myPOPGOES', 'cG8_uoCVErw'],
    ['Searching - myPOPGOES', 'fk9U-t-VPGc'],
    ['Mysterious - myPOPGOES', 'X9X8ZYCmBj4'],
    ['Main Theme - myPOPGOES', 'd0-xBEn_X7Q'],
    ['Challenge - myPOPGOES', 'ccxf2gUyEDw'],
    ['Fishing - myPOPGOES', 'TsVup12XEm0'],
    ['Topping Juggle - myPOPGOES', 'DO9TnE_H0O0'],
    ['Longest Popgoes - myPOPGOES', 'e3cqE_38xvg'],
    ['Pest Control - myPOPGOES', 'omF2hmJm1VA'],
    ['Whack-A-Rabbit - myPOPGOES', 'NoiRhdewdEg'],
    ['Complete Ending - myPOPGOES', 'VQVDsqNEqUg'],
    ['My Bonnie - myPOPGOES', 'jQCsMa0BNZM'],

    //tjoc
    ['Main Menu - THE JOY OF CREATION', 'ezNCjmUrjgk'],

];